language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - npm install -g gulp-cli
  - yarn install
  - composer install -o --no-dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - gulp
  - cd vendor/boldgrid/library/; gulp build; cd

script:
  - find . -name '*.php' -exec php -lf {} \; > /dev/null
  - phpunit --debug
  - yarn run php-codesniffer
  - yarn run js-lint

deploy:
  - provider: script
    script: chmod +x ./node_modules/@boldgrid/wordpress-tag-sync/release.sh && ./node_modules/@boldgrid/wordpress-tag-sync/release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "boldgrid-backup.zip"
    skip_cleanup: true
    on:
      tags: true
