language: php

dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change
  slack: "${SLACK_AUTH}"

php:
  - 7.1
  - 5.6

before_script:
  - nvm install 10
  - nvm use 10
  - yarn install
  - composer install -o --no-dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - find . -name composer -prune -o -name node_modules -prune -o -name '*.php' -exec php -lf {} \; > /dev/null
  - phpunit --debug --coverage-clover=coverage.xml
  - yarn run php-codesniffer
  - yarn run js-lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: chmod +x ./node_modules/@boldgrid/wordpress-tag-sync/release.sh && ./node_modules/@boldgrid/wordpress-tag-sync/release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "boldgrid-backup.zip"
    on:
      tags: true
