language: php

# Distrubution / environments: https://docs.travis-ci.com/user/reference/overview/
# Ubuntu Trusty does not support php8: https://docs.travis-ci.com/user/languages/php/
dist: xenial

services:
  # Specifically including MySQL was not needed with Trusty, but other environments do need it.
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: "GYRxUZH53f/OdEhgn4w908Ivuyl4h/p05kR1Buv0ovDEiSbuesWvqa3LMlXy8J67dLZpkFxToM4tlNCFdykNNHnKLHb1EqgjShIpRcgKppOA0L/87UrtjS+5OhAJAghnQr8KOuj+Ivn7zFVHS8+WBvLWKEeP7zrW/K1IqNrvUjzVcg9xSzLL/q6l/yLaAxqtCX4jXudg5HmtK7QTTQEjFSnnNW4J4hWbrKGHH43C5+9msUT7Mqo3mNjJf1tKGm+HJ5NN2wk3x/SzVEFdUJIUoFVAoG1CjOZKPqfKi7I9VStaC6sGhhiq53Sn7rbmbPJqH3ZD+Q3GaE/sqc5RxuC/34Bn1rGPs3H7RGi5DAAz7f5fHpaZWsux4b+QvLwVx7FHky44uGzPPgzN7+jJxwXh1RBd6yZq6551mHDvOdF77RPJlTJ1UukqQFjqMLNUISX9Pv6cQPealEXjFM7fOMofGyIAkJQusDczIekIZqB5W44i4XwBjKMky+47CZK9Ac41HSpJdpLs+jVa1G7N8Kb/mNSzGx4ABGbXLt+V0YphAL2+WPJ1DEYRZZVCcEzwJl/M5CFOBiUAcd9B3ZpFXoYBxyfjReJFUY7xMVozRXB7hu6RatmLhh+mYbL48572eq01wMxtfr/Klr82PwzoSX5qujWZv2ksxJTiRbPJcBk22YQ="

matrix:
  include:
    - php: 5.6
      before_script:
        - nvm install 10
        - nvm use 10
        - yarn install
        - composer self-update --1
        # Lock file has phpunit 7. Remove it and install phpunit 5 for php 5.6.
        - composer remove --dev phpunit/phpunit
        - composer require --dev phpunit/phpunit ^5
        - composer install -o
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - php: 7.4
      before_script:
        - nvm install 10
        - nvm use 10
        - yarn install
        - composer self-update --1
        # Lock file has phpunit 7. Remove it and install phpunit for this environment.
        - composer remove --dev phpunit/phpunit
        - composer require --dev phpunit/phpunit
        - composer install -o
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - php: 8.0
      before_script:
        - nvm install 10
        - nvm use 10
        - yarn install
        - composer self-update --1
        # Lock file has phpunit 7. Remove it and install phpunit for this environment.
        - composer remove --dev phpunit/phpunit
        - composer require --dev phpunit/phpunit
        - composer install -o
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - find . -name composer -prune -o -name node_modules -prune -o -name '*.php' -exec php -lf {} \; > /dev/null
  - vendor/phpunit/phpunit/phpunit --debug
  #
  - composer create-project wp-coding-standards/wpcs --no-dev
  #- composer require --dev squizlabs/php_codesniffer
  # - yarn run install-codesniffs
  - wpcs/vendor/bin/phpcs --config-set installed_paths wpcs
  - wpcs/vendor/bin/phpcs -p -s --report=emacs --report-width=220 --standard=WordPress-Docs --standard=WordPress-Extra --ignore=*/node_modules/*,*/vendor/* --extensions=php .
  # - yarn run php-codesniffer
# Temp. Different results in wpbex2 vs travix.
#  - yarn run js-lint
  # Composer install was run above in the matrix, and included dev scripts. Run it again with --no-dev
  # to remove them.
  - composer install -o --no-dev

deploy:
  - provider: script
    script: chmod +x ./bin/release.sh && ./bin/release.sh
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "boldgrid-backup.zip"
    on:
      tags: true
