language: php

services:
  # Specifically including MySQL was not needed with Trusty, but other environments do need it.
  - mysql

notifications:
  slack:
    secure: "GYRxUZH53f/OdEhgn4w908Ivuyl4h/p05kR1Buv0ovDEiSbuesWvqa3LMlXy8J67dLZpkFxToM4tlNCFdykNNHnKLHb1EqgjShIpRcgKppOA0L/87UrtjS+5OhAJAghnQr8KOuj+Ivn7zFVHS8+WBvLWKEeP7zrW/K1IqNrvUjzVcg9xSzLL/q6l/yLaAxqtCX4jXudg5HmtK7QTTQEjFSnnNW4J4hWbrKGHH43C5+9msUT7Mqo3mNjJf1tKGm+HJ5NN2wk3x/SzVEFdUJIUoFVAoG1CjOZKPqfKi7I9VStaC6sGhhiq53Sn7rbmbPJqH3ZD+Q3GaE/sqc5RxuC/34Bn1rGPs3H7RGi5DAAz7f5fHpaZWsux4b+QvLwVx7FHky44uGzPPgzN7+jJxwXh1RBd6yZq6551mHDvOdF77RPJlTJ1UukqQFjqMLNUISX9Pv6cQPealEXjFM7fOMofGyIAkJQusDczIekIZqB5W44i4XwBjKMky+47CZK9Ac41HSpJdpLs+jVa1G7N8Kb/mNSzGx4ABGbXLt+V0YphAL2+WPJ1DEYRZZVCcEzwJl/M5CFOBiUAcd9B3ZpFXoYBxyfjReJFUY7xMVozRXB7hu6RatmLhh+mYbL48572eq01wMxtfr/Klr82PwzoSX5qujWZv2ksxJTiRbPJcBk22YQ="

matrix:
  include:
    -
      php: 7.4
      dist: bionic
      before_script:
        - nvm install 10
        - nvm use 10
        - yarn install
        - composer self-update --1
        - composer remove --dev phpunit/phpunit && composer require --dev phpunit/phpunit
        - composer install -o
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    -
      php: 8.0
      dist: xenial
      before_script:
        - nvm install 10
        - nvm use 10
        - yarn install
        - composer self-update --1
        - composer remove --dev phpunit/phpunit && composer require --dev phpunit/phpunit
        - composer install -o
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - find . \( -name composer -o -name node_modules -o -name phpunit -o -name phpunit-polyfills -o -name code-unit-reverse-lookup \) -prune -o -name '*.php' -exec php -lf {} \; > /dev/null
  - vendor/phpunit/phpunit/phpunit --debug --verbose
  - yarn run js-lint
  # Remove dev scripts.
  - composer install -o --no-dev

before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install faraday-net_http -v '3.3.0'
  - gem install uri
  - gem install logger

deploy:
  - provider: script
    script: chmod +x ./bin/release.sh && ./bin/release.sh
    skip_cleanup: true
    on:
      tags: true
      php: 7.4
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "boldgrid-backup.zip"
    skip_cleanup: true
    on:
      tags: true
      php: 7.4
