language: php

notifications:
  email:
    on_success: never
    on_failure: change

dist: precise

php:
# Taking out php 5.3 support
# https://bbpress.trac.wordpress.org/ticket/3127
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

sudo: required

before_script:
  - composer update
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  # Install yarn.
  # https://yarnpkg.com/lang/en/docs/install-ci/
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  - yarn: true

script:
  - phpunit --debug
  - yarn js-lint --log-level=debug
